/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { LeaveRequest } from "./LeaveRequest";
import { LeaveRequestCountArgs } from "./LeaveRequestCountArgs";
import { LeaveRequestFindManyArgs } from "./LeaveRequestFindManyArgs";
import { LeaveRequestFindUniqueArgs } from "./LeaveRequestFindUniqueArgs";
import { DeleteLeaveRequestArgs } from "./DeleteLeaveRequestArgs";
import { LeaveRequestService } from "../leaveRequest.service";
@graphql.Resolver(() => LeaveRequest)
export class LeaveRequestResolverBase {
  constructor(protected readonly service: LeaveRequestService) {}

  async _leaveRequestsMeta(
    @graphql.Args() args: LeaveRequestCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [LeaveRequest])
  async leaveRequests(
    @graphql.Args() args: LeaveRequestFindManyArgs
  ): Promise<LeaveRequest[]> {
    return this.service.leaveRequests(args);
  }

  @graphql.Query(() => LeaveRequest, { nullable: true })
  async leaveRequest(
    @graphql.Args() args: LeaveRequestFindUniqueArgs
  ): Promise<LeaveRequest | null> {
    const result = await this.service.leaveRequest(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => LeaveRequest)
  async deleteLeaveRequest(
    @graphql.Args() args: DeleteLeaveRequestArgs
  ): Promise<LeaveRequest | null> {
    try {
      return await this.service.deleteLeaveRequest(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
