/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { ApprovalLevel } from "./ApprovalLevel";
import { ApprovalLevelCountArgs } from "./ApprovalLevelCountArgs";
import { ApprovalLevelFindManyArgs } from "./ApprovalLevelFindManyArgs";
import { ApprovalLevelFindUniqueArgs } from "./ApprovalLevelFindUniqueArgs";
import { DeleteApprovalLevelArgs } from "./DeleteApprovalLevelArgs";
import { ApprovalLevelService } from "../approvalLevel.service";
@graphql.Resolver(() => ApprovalLevel)
export class ApprovalLevelResolverBase {
  constructor(protected readonly service: ApprovalLevelService) {}

  async _approvalLevelsMeta(
    @graphql.Args() args: ApprovalLevelCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [ApprovalLevel])
  async approvalLevels(
    @graphql.Args() args: ApprovalLevelFindManyArgs
  ): Promise<ApprovalLevel[]> {
    return this.service.approvalLevels(args);
  }

  @graphql.Query(() => ApprovalLevel, { nullable: true })
  async approvalLevel(
    @graphql.Args() args: ApprovalLevelFindUniqueArgs
  ): Promise<ApprovalLevel | null> {
    const result = await this.service.approvalLevel(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => ApprovalLevel)
  async deleteApprovalLevel(
    @graphql.Args() args: DeleteApprovalLevelArgs
  ): Promise<ApprovalLevel | null> {
    try {
      return await this.service.deleteApprovalLevel(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
