/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { ProcessService } from "../process.service";
import { ProcessCreateInput } from "./ProcessCreateInput";
import { Process } from "./Process";
import { ProcessFindManyArgs } from "./ProcessFindManyArgs";
import { ProcessWhereUniqueInput } from "./ProcessWhereUniqueInput";
import { ProcessUpdateInput } from "./ProcessUpdateInput";
import { TaskFindManyArgs } from "../../task/base/TaskFindManyArgs";
import { Task } from "../../task/base/Task";
import { TaskWhereUniqueInput } from "../../task/base/TaskWhereUniqueInput";

export class ProcessControllerBase {
  constructor(protected readonly service: ProcessService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Process })
  async createProcess(
    @common.Body() data: ProcessCreateInput
  ): Promise<Process> {
    return await this.service.createProcess({
      data: data,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        description: true,
        name: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [Process] })
  @ApiNestedQuery(ProcessFindManyArgs)
  async processes(@common.Req() request: Request): Promise<Process[]> {
    const args = plainToClass(ProcessFindManyArgs, request.query);
    return this.service.processes({
      ...args,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        description: true,
        name: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Process })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async process(
    @common.Param() params: ProcessWhereUniqueInput
  ): Promise<Process | null> {
    const result = await this.service.process({
      where: params,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        description: true,
        name: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Process })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateProcess(
    @common.Param() params: ProcessWhereUniqueInput,
    @common.Body() data: ProcessUpdateInput
  ): Promise<Process | null> {
    try {
      return await this.service.updateProcess({
        where: params,
        data: data,
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
          description: true,
          name: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Process })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteProcess(
    @common.Param() params: ProcessWhereUniqueInput
  ): Promise<Process | null> {
    try {
      return await this.service.deleteProcess({
        where: params,
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
          description: true,
          name: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Get("/:id/tasks")
  @ApiNestedQuery(TaskFindManyArgs)
  async findTasks(
    @common.Req() request: Request,
    @common.Param() params: ProcessWhereUniqueInput
  ): Promise<Task[]> {
    const query = plainToClass(TaskFindManyArgs, request.query);
    const results = await this.service.findTasks(params.id, {
      ...query,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        name: true,
        status: true,
        dueDate: true,
        description: true,

        process: {
          select: {
            id: true,
          },
        },
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/tasks")
  async connectTasks(
    @common.Param() params: ProcessWhereUniqueInput,
    @common.Body() body: TaskWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      tasks: {
        connect: body,
      },
    };
    await this.service.updateProcess({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/tasks")
  async updateTasks(
    @common.Param() params: ProcessWhereUniqueInput,
    @common.Body() body: TaskWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      tasks: {
        set: body,
      },
    };
    await this.service.updateProcess({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/tasks")
  async disconnectTasks(
    @common.Param() params: ProcessWhereUniqueInput,
    @common.Body() body: TaskWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      tasks: {
        disconnect: body,
      },
    };
    await this.service.updateProcess({
      where: params,
      data,
      select: { id: true },
    });
  }
}
